### ISSUE TITLE
"TYPE hs110_total gauge"

### ISSUE THREAD

**Issue by AndrStnz** [sdelrio/hs110-prometheus-exporter#13]
Hi!

first of all, thank you very much for your great work! I really really appreciate this exporter.

I have a minor issue:

"TYPE hs110_total gauge" should be a Counter and not a Gauge

`"A gauge is a metric that represents a single numerical value that can arbitrarily go up and down."`

And the Total Power should only go up and up only :) So...

`A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart`

sounds way better

This being a Gauge breakes some promQL stuff so...

Thanks! :)

**Comment by AndrStnz** [comment]
So I got my promQL to work, so I revoke my statement that it breaks PromQL stuff.
The increase() function of promQL is originally intended for counters but still works with gauges *yay*
But I stand by the it "should be a counter" one. (because of the up up nature)

I could understand not "fixing" it because it calls for yet another prometheus_client module to be imported into the script so... I have no idea how much work this is...

In case someone really needs a counter instead of a gauge:
`curl -s 127.0.0.1:8110 | tail -n 3 | sed 's/gauge/counter/' > /etc/prometheus/node_exporter/textfile/YOUR_METRIC_HERE.prom`

Really ugly, but it gets the job done. _cries himself to sleep at night_ 

Cheers.

**Comment by sdelrio** [comment]
I don't remember exactly why I setup that to Gauge, probably because I don't use it at all on my graphs.

 if you poweroff and poweron the hs110 the value goes back to 0, but the documentation says that "A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart". So this won't be a problem

If the current database have stored that Gague and you change, perhaps it will break. Let me setup a dev env and test. In the worst case I could setup and extra counter with another name.

**Comment by sdelrio** [comment]
mm I saw why I setup to gauge.

The HS110 gives you an absolute value, not an increment. So I should store it and calculate the increments. But if i do, when the exporter is stopped, it won't keep that value, and won't measuere that total for the time the exporter has been down. So that value would be false

**Comment by sdelrio** [comment]
https://github.com/prometheus/client_python#counter

By design, I cannot increase counters with a function so I cannot take that substraction and the increment can't be done.

This kind if counter is for other things like, counting exceptions inside the program or number of visits o a real counter. This doesn't seems to be the case.

**Comment by sdelrio** [comment]
Sample

t= 0,   total=0, test_counter=0
t= 1s,   total=1, test_counter=¿1-0? ¿how I know when tu substract, each http reequest? no,
t= 2s,   total=2, test_counter=¿2-1? how I know when I had to save the previous value to 1
t= 3s,   total=3, test_counter=?
t= 4s,   total=4, test_counter=?
...
t= 100s, total=100, test_counter =?
t= 101s, , total=100, test_counter =?

**Comment by AndrStnz** [comment]
Oh, does the hs110 not just send the "total power" back? I have no clue whats happening inside the tplink protocol... So if there is anything more involved than a simple "query total power" then i would call it a day 😄 

Thanks for your work! :) 

My specific usecase for a counter is:
`increase(hs110_total{instance="...",job="hs110_exporter"}[24h])`
I want to know how much energy has been consumed in the last 'n' hours.

Usually you have to use a counter for that, but it seems to work with this gauge just fine... So no worries.

**Comment by sdelrio** [comment]
I use this to paint histogram: `hs110_power_watt[1h]`  and then multiplyl by kW/h to get the cost.
