### ISSUE TITLE
Influxdb Support

### ISSUE THREAD

**Issue by xInsertx** [sdelrio/hs110-prometheus-exporter#8]
Any chance to add influxdb support? I have a basic script I've been using, but having a nice docker image would be great.

A bonus would be if you could add a tag for device name and location/group (set by env var) so you can do more filtering in grafana etc.

**Comment by sdelrio** [comment]
I don't know how influxdb works at the moment neither have an influxdb server to test,
The project was designed only for prometheus (that's why the name is prometheus-exporter). But I guess the class can be used for that if with influxdb you can send a function (like the lambda funcion I use for prometheus).

Adding a tag for location is something that I was thinking but then, should I run one exporter for each hs110 or make one exporter that read from many hs110? I just use one hs110 but if some people will use several I think I can add it. If you want it, please open a different issue just with "Add tag for hs110 device" with all the details you would want, for example 1 tag with just device name, or 3 tags: name, location, group, ...

**Comment by xInsertx** [comment]
Would it help if I gave you an example? This was just a slightly modified version to what I was using. I was going to change it to use switches than run it via cron (for device ip, etc), but got lazy and just add a new one for each unit.

[hs110-collector.txt](https://github.com/sdelrio/hs110-prometheus-exporter/files/3934631/hs110-collector.txt)

So from your script perspective, I would assume you would use vars, db_type, db_ip, db_port, etc to support both types (along with the hs110 ip and frequency). You than would set your connection method based on db_type.

As for tags; I would set the device name as a required var, then if you decided to add more they could be optional (just set as 'default' or 'none' if null so they are still populated)

**Comment by xInsertx** [comment]
As for multiple devices, while running 1 docker instance would be better, if the image was light enough id just as happily run one for each device. 

But if you wanted to use a single instance, then I think you would need to use a config file that you would read through instead of the variable because it wouldn't work for many. Something like a xml, json or yml file would be fine. (device ip, the tags you use, etc).

EDIT: I should mention the script above only has 'name' and 'group' because I have a default value used for null in influxdb and just forgot to update that copy. My other scripts use location aswell.

**Comment by sdelrio** [comment]
Memory usage is low I think, anyway. I think the first step would be to make the tags for the location part, and then the project must be splitted in a general library for hs110 management and then use that lib into hs110-prometheus-exporter and then create another hss10-influxdb-exporter:

![image](https://user-images.githubusercontent.com/12765729/70375229-9f7f4f00-18fb-11ea-8ff5-cde98f5faedf.png)

**Comment by sdelrio** [comment]
If you want to dockerize your script just reuse the Dockerfile, and add your requirement.txt and python files:

https://github.com/sdelrio/hs110-prometheus-exporter/blob/master/Dockerfile

Just released a more clean version with standard python base image.
